services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    cap_add:
      - NET_ADMIN # required for tc
    ports:
      - "5332:5432"
